# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'AB-Salon' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"

  # Pods for AB-Salon

  target 'AB-SalonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AB-SalonUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
